group: travis_latest
matrix:
  include:
    - language: python
      cache: pip
      python: 3.6
      before_script:
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
        - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      allow_failures:
        - python: nightly
        - python: pypy3
      install:
        - pip install flake8  # pytest  # add another testing frameworks later
    - language: node_js
      node_js: "9.9"
      install:
        - yarn
      script:
        - yarn run lint
    - language: ruby
      rvm:
        - 2.5.0
      before_script:
        - gem install rubocop
      script:
        - rubocop
script:
  - true
notifications:
  on_failure: change 
